# Site settings
title: CCISEL
header-img: img/home-bg.jpg
email: direccao@cc.isel.ipl.pt
description: "CCISEL web site"
url: "https://ccisel.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins:
  - jekyll-feed
