# Site settings
title: CCISEL
header-img: img/home-bg.jpg
email: direccao@cc.isel.ipl.pt
description: "CCISEL web site"
url: "https://cc.isel.ipl.pt/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins:
  - jekyll-feed
